# config.py
# Stałe konfiguracyjne projektu Library Ghost.

SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
FPS = 60

WINDOW_TITLE = "Library Ghost"

PLAYER_START_X = SCREEN_WIDTH / 2
PLAYER_START_Y = SCREEN_HEIGHT / 2
PLAYER_RADIUS = 18
PLAYER_SPEED = 230
PLAYER_MAX_ENERGY = 100
